# Generated by Django 3.0.2 on 2020-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='first',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='last',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
