# Generated by Django 3.0.2 on 2020-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20200126_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='last',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
